### ISSUE TITLE
line ending issue

### ISSUE THREAD

**Issue by dantman** [zkochan/zx#1]
`zx` in npm seems to use `\r` for line breaks instead of `\n` which breaks the shebang

**Comment by zkochan** [comment]
Thanks for noticing. I converted all the line endings to `\n` in v0.1.2

Where did it not work? On Linux?

**Comment by dantman** [comment]
OS X. But I expect the same will hold true for most unix-like or posix based systems.

**Comment by zkochan** [comment]
Unfortunately I cannot check it on OS X but if the issue is gone, fill free to close it

**Comment by dantman** [comment]
Yup, works
